# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-15 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('loinc_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestRagnes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_sex', models.CharField(max_length=1)),
                ('age_range_lower_days', models.IntegerField()),
                ('age_range_upper_days', models.IntegerField()),
                ('test_reference_range_lower', models.FloatField()),
                ('test_reference_range_upper', models.FloatField()),
                ('test_low_critical_value', models.FloatField()),
                ('test_high_critical_value', models.FloatField()),
                ('test_units', models.CharField(max_length=10)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagegenerator.LabTest')),
            ],
        ),
    ]
