# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-15 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestRagnes',
            new_name='TestRanges',
        ),
    ]
