# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0002_auto_20170315_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fhir_id', models.CharField(max_length=50)),
                ('ssn', models.CharField(max_length=9)),
                ('birthday', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=10)),
                ('michigan_common_key_service_identifier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fhir_id', models.CharField(max_length=50)),
                ('ssn', models.CharField(max_length=9)),
                ('national_provider_identifier', models.CharField(max_length=50)),
                ('michigan_common_key_service_identifier', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='ordering_practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messagegenerator.Practitioner'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messagegenerator.Patient'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagegenerator.LabTest'),
        ),
    ]
