# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0003_auto_20170316_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='testranges',
            name='has_lower_critical_range',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testranges',
            name='has_upper_critical_range',
            field=models.BooleanField(default=True),
        ),
    ]
