# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-11 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0007_auto_20170411_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='care_team_doctor_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordermessage_related_created', to='messagegenerator.Practitioner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='care_team_doctor_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ordermessage_related_created_here', to='messagegenerator.Practitioner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='room',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='value',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='ordering_practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordermessage_related', to='messagegenerator.Practitioner'),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagegenerator.Patient'),
        ),
    ]
