# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-12 00:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0010_auto_20170412_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='time_ordered',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 0, 54, 51, 7081)),
        ),
    ]
