# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0013_auto_20170412_1448'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='ordermessage',
        #     name='claiming_practitioner',
        # ),
        # migrations.AddField(
        #     model_name='ordermessage',
        #     name='claiming_practitioner',
        #     field=models.CharField(default=None, max_length=100),
        # ),
    ]
