# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-12 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0017_auto_20170412_1451'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='ordermessage',
        #     name='claiming_practitioner',
        # ),
        # migrations.AddField(
        #     model_name='ordermessage',
        #     name='claimed_by',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordermessage_related_created_claimed', to='messagegenerator.Practitioner'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='practitioner',
            name='location',
            field=models.IntegerField(default=2),
        ),
    ]
