# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-12 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0018_auto_20170412_1452'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='ordermessage',
        #     name='claimed_by',
        # ),
        migrations.AlterField(
            model_name='ordermessage',
            name='time_ordered',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 18, 54, 50, 61165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='location',
            field=models.IntegerField(default=1),
        ),
    ]
