# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-12 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0019_auto_20170412_1454'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='ordermessage',
        #     name='claimer',
        #     field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordermessage_related_created_here_', to='messagegenerator.Practitioner'),
        # ),
        migrations.AlterField(
            model_name='ordermessage',
            name='time_ordered',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 19, 1, 39, 153874, tzinfo=utc)),
        ),
    ]
