# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-12 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0021_auto_20170412_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='push_token',
            field=models.CharField(default='123', max_length=500),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='time_ordered',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 19, 8, 13, 118363, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='location',
            field=models.IntegerField(default=3),
        ),
    ]
