# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-15 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0023_auto_20170412_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='push_message',
            field=models.CharField(default='push notification', max_length=250),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='time_ordered',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 18, 4, 59, 549451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='location',
            field=models.IntegerField(default=1),
        ),
    ]
