# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-20 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0024_auto_20170415_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='reference_range',
            field=models.CharField(default='1.0 - 2.0', max_length=250),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='time_ordered',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 20, 59, 15, 968936, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='location',
            field=models.IntegerField(default=2),
        ),
    ]
