# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-26 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messagegenerator', '0025_auto_20170420_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermessage',
            name='room',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='time_ordered',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 19, 17, 52, 953383, tzinfo=utc)),
        ),
    ]
